version: 1
formatters:
  simple:
    format: '[%(levelname)s] - %(message)s'
  full:
    format: '[%(asctime)s %(levelname)s][%(filename)s:%(lineno)s - %(funcName)s] - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: full
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    formatter: full
    mode: a
    # relative to the job log directory
    filename: ${hydra.run.dir}/${hydra.job.name}.log
  
root:
  level: INFO
  handlers: [console, file]

disable_existing_loggers: false