name: SwinV2-T
num_classes: 1000
img_size: 256
patch_size: 4
in_chans: 3
embed_dim: 96
depths: [2, 2, 6, 2]
num_heads: [3, 6, 12, 24]
window_size: 8
mlp_ratio: 4
qkv_bias: True
ape: False
patch_norm: True
pretrained_window_sizes: [0, 0, 0, 0]
use_checkpoint: False

object:
  _target_: calibrate.net.swin.swin_transformer_v2.SwinTransformerV2
  img_size: ${model.img_size}
  patch_size: ${model.patch_size}
  in_chans: ${model.in_chans}
  num_classes: ${model.num_classes}
  embed_dim: ${model.embed_dim}
  depths: ${model.depths}
  window_size: ${model.window_size}
  mlp_ratio: ${model.mlp_ratio}
  qkv_bias: ${model.qkv_bias}
  drop_rate: 0.0
  drop_path_rate: 0.1
  use_checkpoint: ${model.use_checkpoint}
  fused_window_process: False


