name: cosine
min_lr: 5e-6  # for batch_size 512
warmup_lr: 5e-7  # for batch size 512
warmup_epochs: 1
decay_rate: 0.1

object:
  _target_: timm.scheduler.cosine_lr.CosineLRScheduler
  t_initial: ${train.max_epoch}
  t_mul: 1
  lr_min: ${lr_scheduler.min_lr}
  decay_rate: ${lr_scheduler.decay_rate}
  warmup_lr_init: ${lr_scheduler.warmup_lr}
  warmup_t: ${lr_scheduler.warmup_epochs}
  cycle_limit: 1
  t_in_epochs: True


