name: multi_step
decay_t: [40, 60]
decay_rate: 0.1

object:
  _target_: timm.scheduler.multistep_lr.MultiStepLRScheduler
  decay_t: ${lr_scheduler.decay_t}
  decay_rate: ${lr_scheduler.decay_rate}
  t_in_epochs: True