name: step
decay_t: 40
decay_rate: 0.1
warmup_t: 0
warmup_lr: 5e-7
t_in_epochs: True

object:
  _target_: timm.scheduler.step_lr.StepLRScheduler
  decay_t: ${lr_scheduler.decay_t}
  decay_rate: ${lr_scheduler.decay_rate}
  warmup_t: ${lr_scheduler.warmup_t}
  warmup_lr_init: ${lr_scheduler.warmup_lr}
  t_in_epochs: ${lr_scheduler.t_in_epochs}